server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/manufabri91/api-config-store
          search-paths:
          - '*api'
